name: Auto Update Global News

on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *' # Chạy mỗi tiếng 1 lần cho nó nóng

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: # PHẢI CÓ DÒNG NÀY ĐỂ FIX LỖI 128
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4 # Dùng v4 cho mới, fix cảnh báo Node.js 20

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Dependencies
        run: pip install feedparser beautifulsoup4 google-generativeai

      - name: Run Script
        env:
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
        run: python bot_rss.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "BrokeNoMore Bot"
          git config --global user.email "bot@brokenomore.com"
          git add .
          git commit -m "Update Market Terminal [skip ci]" || exit 0
          git push
